[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agentclass"
version = "0.0.9"
description = "AgentClass"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "agentmodel==0.0.2",
]

