[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agentclass"
version = "0.0.7"
description = "AgentClass"
readme = "README.md"
requires-python = ">=3.9"

