name: Publish to PyPI

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: publish-pypi
              uses: ./.github/actions/publish-pypi
              with:
                github-token: ${{ github.token }}

                # TODO: this is only required if referencing a local action
                checkout: false
                pypi-github-org: bitovi
                pypi-github-repo: PyPI
                pypi-github-workflow-ref: initial-working