name: Publish to PyPI

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: publish-pypi
              uses: ./.github/actions/publish-pypi
              with:
                  # github_token: ${{ github.token }}
                pypi-github-org: bitovi
                pypi-github-repo: PyPI
                pypi-github-workflow-ref: initial-working