name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: publish-pypi
              uses: bitovi/github-actions-publish-github-pypi@main
              with:
                github-token: ${{ secrets.BITOVI_PYPI_GITHUB_TOKEN_FINEGRAINED }}
                pypi-github-org: bitovi
                pypi-github-repo: PyPI
                pypi-github-workflow-filename: publish-trigger.yaml